/**
 * 兜底数据 - 当 Supabase 未配置时使用
 * 这些数据保证网站在无数据库时也能正常展示
 */

export const fallbackArticles = [
  {
    id: '1',
    title: 'S7-1200 PID 控制从入门到精通',
    slug: 'siemens-s7-1200-pid',
    excerpt: '深入讲解西门子 S7-1200 PLC 的 PID 控制原理与实战应用，包含参数整定、自整定和串级控制。',
    cover_image: '',
    category: 'PLC编程',
    tags: ['S7-1200', 'PID', 'TIA Portal'],
    is_premium: false,
    published: true,
    featured: true,
    created_at: '2026-05-20T00:00:00Z',
    author: { display_name: '易牧' },
  },
  {
    id: '2',
    title: '数字孪生技术在智能制造实训中的应用',
    slug: 'digital-twin-training',
    excerpt: '探讨如何利用数字孪生技术构建虚拟工厂，让学生在安全环境中掌握智能制造全流程。',
    cover_image: '',
    category: '数字孪生',
    tags: ['数字孪生', 'Unity3D', '实训'],
    is_premium: true,
    published: true,
    featured: true,
    created_at: '2026-05-18T00:00:00Z',
    author: { display_name: '易牧' },
  },
  {
    id: '3',
    title: 'ESP32 Modbus TCP 通信实战',
    slug: 'esp32-modbus-tcp',
    excerpt: '使用 ESP32 通过 Modbus TCP 协议与西门子 PLC 通信，实现工业物联网数据采集。',
    cover_image: '',
    category: 'IoT开发',
    tags: ['ESP32', 'Modbus', '物联网'],
    is_premium: false,
    published: true,
    featured: false,
    created_at: '2026-05-15T00:00:00Z',
    author: { display_name: '易牧' },
  },
  {
    id: '4',
    title: 'AI 赋能 MCU 开发：从 GPT 到代码生成',
    slug: 'ai-mcu-development',
    excerpt: '如何利用 AI 大模型加速单片机开发？从需求分析到代码生成的全流程实践。',
    cover_image: '',
    category: 'AI赋能',
    tags: ['AI', 'MCU', 'ESP32-S3'],
    is_premium: true,
    published: true,
    featured: false,
    created_at: '2026-05-10T00:00:00Z',
    author: { display_name: '易牧' },
  },
  {
    id: '5',
    title: '大学 PLC 课程应该怎么教？',
    slug: 'plc-teaching-methodology',
    excerpt: '反思当前高校 PLC 教学的痛点，提出"虚实结合、项目驱动"的教学改革思路。',
    cover_image: '',
    category: '创业实践',
    tags: ['PLC', '教学改革', '实训'],
    is_premium: false,
    published: true,
    featured: false,
    created_at: '2026-05-05T00:00:00Z',
    author: { display_name: '易牧' },
  },
]

export const fallbackArticleCategories = ['全部', 'PLC编程', '数字孪生', 'IoT开发', 'AI赋能', '数学教育', '创业实践']

export const fallbackCourses = [
  {
    id: '1',
    title: '西门子 S7-1200 PLC 从入门到精通',
    slug: 's7-1200-complete',
    description: '零基础系统学习 S7-1200 PLC 编程，覆盖梯形图、SCL、HMI、通信等核心技能。',
    cover_image: '',
    level: '入门',
    is_premium: false,
    price: 0,
    published: true,
    chapters_count: 24,
    students_count: 1280,
    status: 'available',
    lessons: 24,
    duration: '48小时',
    tags: ['PLC', 'S7-1200', 'TIA Portal'],
    icon: '🔧',
    color: 'from-blue-400 to-blue-600',
  },
  {
    id: '2',
    title: '数字孪生工厂实战营',
    slug: 'digital-twin-bootcamp',
    description: '手把手教你用 Unity3D 构建数字孪生工厂，包含建模、动画、数据绑定全流程。',
    cover_image: '',
    level: '进阶',
    is_premium: true,
    price: 199,
    published: true,
    chapters_count: 18,
    students_count: 456,
    status: 'available',
    lessons: 18,
    duration: '36小时',
    tags: ['数字孪生', 'Unity3D', '工厂仿真'],
    icon: '🏭',
    color: 'from-purple-400 to-purple-600',
  },
  {
    id: '3',
    title: 'ESP32 工业物联网全栈开发',
    slug: 'esp32-iiot',
    description: 'ESP32-S3 + MQTT + Modbus + Node-RED 打造完整的工业物联网解决方案。',
    cover_image: '',
    level: '进阶',
    is_premium: true,
    price: 99,
    published: true,
    chapters_count: 16,
    students_count: 312,
    status: 'available',
    lessons: 16,
    duration: '32小时',
    tags: ['ESP32', 'MQTT', 'Modbus', 'Node-RED'],
    icon: '🌐',
    color: 'from-orange-400 to-orange-600',
  },
  {
    id: '4',
    title: 'AI-Edge32 Pro 实验套件教程',
    slug: 'ai-edge32-pro',
    description: '配套 AI-Edge32 Pro 实验套件的完整教程，14个外设实验轻松掌握嵌入式开发。',
    cover_image: '',
    level: '入门',
    is_premium: false,
    price: 0,
    published: true,
    chapters_count: 14,
    students_count: 892,
    status: 'available',
    lessons: 14,
    duration: '28小时',
    tags: ['ESP32-S3', 'AI', '实验套件'],
    icon: '🤖',
    color: 'from-green-400 to-green-600',
  },
]

export const fallbackProducts = [
  {
    id: '1', name: 'AI-Edge32 Pro 开发套件', slug: 'ai-edge32-pro',
    subtitle: '入门级 ESP32-S3 AI 边缘计算',
    description: '基于 ESP32-S3 的 AI 边缘计算开发套件，14 个外设模块，配套完整实验教程。',
    price: '¥199', price_note: '起', image: '', category: 'ESP32', buy_url: '', published: true,
    icon: '🤖', color: 'from-blue-400 to-blue-600', status: 'available',
    features: ['ESP32-S3 双核处理器', '14 个外设模块', '14 个配套实验', 'KiCad 8 开源 PCB'],
    tags: ['ESP32-S3', 'AI', '入门套件', '教学版'],
  },
  {
    id: '2', name: 'Modbus TCP 通信模块', slug: 'modbus-tcp-module',
    subtitle: '工业级 Modbus TCP 转 RTU 网关',
    description: 'ESP32 + MAX485 工业级 Modbus TCP 转 RTU 网关模块，与西门子 PLC 无缝通信。',
    price: '¥89', price_note: '起', image: '', category: '通信模块', buy_url: '', published: true,
    icon: '🔌', color: 'from-orange-400 to-orange-600', status: 'available',
    features: ['ESP32 + MAX485 方案', 'Modbus TCP/RTU 双协议', '与 S7-1200 联调通过', '开源固件 + 电路图'],
    tags: ['Modbus', 'ESP32', 'PLC通信', '工业物联网'],
  },
  {
    id: '3', name: '数字孪生实训套件', slug: 'digital-twin-kit',
    subtitle: '桌面级数字孪生实训入门',
    description: '含电机、传感器、PLC模拟器的桌面级数字孪生实训套件，配合 Unity3D 虚拟场景。',
    price: '¥499', price_note: '起', image: '', category: '套件', buy_url: '', published: true,
    icon: '🏭', color: 'from-purple-400 to-purple-600', status: 'available',
    features: ['桌面级 PLC 模拟器', '步进电机 + 传感器', 'Unity3D 虚拟场景', '8 个实训实验'],
    tags: ['数字孪生', 'PLC', '实训套件', 'Unity3D'],
  },
]

export const fallbackLabItems = [
  {
    id: '1', name: 'DT-Station Pro 数字孪生实训工作站', slug: 'dt-station-pro',
    description: '数字孪生引擎 + PLC 虚拟化 + 桌面实训台 + 课程包，一站式智能制造实训解决方案。',
    subtitle: '入门级 · 桌面部署 · 开箱即教',
    price: '¥50,000 - 80,000 / 套',
    specs: [
      { label: '尺寸', value: '600×400×200mm' },
      { label: '重量', value: '15kg' },
      { label: '控制器', value: 'S7-1200 虚拟化' },
      { label: '配套课程', value: '8 个实验' },
    ],
    modules: [
      { name: '数字孪生引擎', desc: 'Unity3D 二次开发，3D 工厂仿真' },
      { name: 'PLC 虚拟化', desc: 'Beremiz 开源 Soft PLC 运行环境' },
      { name: '桌面实训台', desc: '含按钮、指示灯、步进电机' },
      { name: '课程包', desc: '8 个实验 + PPT + 教学视频' },
    ],
    category: '实训平台', published: true, color: 'from-blue-400 to-indigo-600',
    badge: '主力产品', badge_color: 'bg-amber-100 text-amber-700',
  },
  {
    id: '2', name: 'SmartMFG Lab 模块化智造产线', slug: 'smartmfg-lab',
    description: 'M1-M6 六大模块自由组合，从单工位到完整产线，覆盖 PLC、机器人、视觉、MES 等核心课程。',
    subtitle: '旗舰方案 · 模块化 · 全专业覆盖',
    price: '¥400,000 - 800,000 / 套',
    specs: [
      { label: '工位', value: '1-6 个模块' },
      { label: '控制器', value: 'S7-1200/1500' },
      { label: '通信', value: 'PROFINET / Modbus TCP' },
      { label: '配套课程', value: '13 门核心课程' },
    ],
    modules: [
      { name: 'M1 数字孪生', desc: '虚拟工厂 + 数据驱动仿真' },
      { name: 'M2 PLC 控制', desc: '梯形图/SCL 程序实时运行' },
      { name: 'M3 工业机器人', desc: 'RobotStudio 离线编程' },
      { name: 'M4 机器视觉', desc: '缺陷检测 + 尺寸测量' },
      { name: 'M5 工业网络', desc: 'PROFINET/MQTT 多协议通信' },
      { name: 'M6 MES 系统', desc: '生产排程 + 质量追溯' },
    ],
    category: '实训平台', published: true, color: 'from-orange-400 to-rose-600',
    badge: '旗舰方案', badge_color: 'bg-purple-100 text-purple-700',
  },
]
